name:  '👑 Epic'
title: '👑 Title'
description: 'Four to six weeks of work composed of multiple features.'
labels: ['epic']
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: 'Problem'
      description: 'What customer problem is to be solved?'
      placeholder:
      value:
    validations:
      required: false

  - type: textarea
    id: child-issues
    attributes:
      label: 'Child issues'
      description:
      placeholder:
      value: |
        **Must ship**
        - [ ] Link
        
        **Should ship**
        - [ ] Link
        
        **Nice to ship**
        - [ ] Link
    validations:
      required: false

  - type: textarea
    id: people
    attributes:
      label: 'People'
      description:
      placeholder:
      value: |
        * **Engineering:** 
        * **Product:** 
        * **Design:** 
        * **DRI:** 
    validations:
      required: false

  - type: textarea
    id: who-is-the-customer
    attributes:
      label: 'Who is the customer?'
      description: 'What are characteristics of one or more customer cohorts?'
      placeholder:
      value:
    validations:
      required: false

  - type: textarea
    id: jobs-to-be-done
    attributes:
      label: 'Jobs to be done (JTBD)'
      description: >
        People "hire" products and services to get a "job" done. Jobs are functional — with emotional and social components.
        People buy a kettle not to boil water, but to prepare a hot beverage for consumption. Jobs are solution agnostic.
        Innovation becomes predictable when "needs" are defined as the metrics customers use to measure success when getting the job done.
        See more [here](https://uxdesign.cc/8-things-to-use-in-jobs-to-be-done-framework-for-product-development-4ae7c6f3c30b/).
      placeholder:
      value: |
        * (Example) Monitor application health to prevent incidents or minimize their impact.
        * 
    validations:
      required: false

  - type: textarea
    id: customer-evidence
    attributes:
      label: 'Customer evidence and JTBD validation'
      description:
      placeholder:
      value: |
        * 
        * 
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: 'Solution'
      description: Define how we'll solve the customer problem and satisfy the jobs to be done. Specify any telemetry needed to track usage. Include mock-ups when possible.
      placeholder:
      value:
    validations:
      required: false

  - type: textarea
    id: expected-outcomes
    attributes:
      label: 'Expected outcomes'
      description: 'Make them measurable.'
      placeholder:
      value: |
        * 
        * 
    validations:
      required: false

  - type: textarea
    id: metrics
    attributes:
      label: 'Metrics'
      description:
      placeholder:
      value: |
        * **Dashboard:** 
        * **Queries:** 
        * **Service Catalog entry:** 
    validations:
      required: false

  - type: textarea
    id: definition-of-done
    attributes:
      label: 'Definition of done'
      description: >
        List clear deliverables, whether that's code, product behavior, a metric, a document, the creation of follow-up issues, or even just a comment that addresses the goal of the issue.
        Include if another stakeholder needs to sign off before calling things done.
        Include clean-up tasks like removing short-lived feature flags, archiving short-lived Slack channels, etc.
      placeholder:
      value: |
        - [ ] Done criteria
        - [ ] Done criteria
    validations:
      required: false

  - type: textarea
    id: release-information
    attributes:
      label: 'Release information'
      description: 🟢 - required 
      placeholder:
      value: |
        - [ ] 🟢 **Release date:** 2022-00-00
        - [ ] ⚪ **Staff-ship date and team post:** 2022-00-00
        - [ ] 🟢 [**Release issue:**](https://github.com/github/releases/issues/new/choose) 
        - [ ] 🟢 [**Roadmap-internal issue:**](https://github.com/github/roadmap-internal/issues/new/choose) 
        - [ ] ⚪ [**Public roadmap issue (generated):**](https://github.com/orgs/github/projects/4247) 
        - [ ] ⚪ [**Docs-content issue:**](https://github.com/github/docs-content/issues/new/choose) 
        - [ ] ⚪ [**Docs-internal PR:**](https://github.com/github/docs-internal/pulls) 
        - [ ] ⚪ [**Security review issue:**](https://github.com/github/security-reviews/issues/new/choose) 
        - [ ] ⚪ [**Safety review issue:**](https://github.com/github/safety-council/issues/new/choose) 
        - [ ] ⚪ [**Legal/privacy review issue:**](https://github.com/github/privacy/issues/new/choose) 
        - [ ] 🟢 [**Changelog PR:**](https://github.com/github/blog/tree/master/_changelog) 
        - [ ] 🟢 [**Release FAQ:**](https://github.com/github/releases#4-begin-writing-the-release-faq) 
    validations:
      required: false

  - type: textarea
    id: how-to-try-it
    attributes:
      label: 'How to try it'
      description:
      placeholder:
      value: |
        * [**Feature flags:**](https://admin.github.com/devtools/feature_flags) 
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: 'Risks'
      description:
      placeholder:
      value:
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: 'Dependencies'
      description:
      placeholder:
      value:
    validations:
      required: false

  - type: textarea
    id: relevant-links
    attributes:
      label: 'Relevant information'
      description:
      placeholder:
      value: |
        * **LinkDescription1:** 
        * **LinkDescription2:** 
    validations:
      required: false
